---
title: "Plasmid_Tree"
author: "Max Cummins"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
#Read in our packages
library(tidyverse)
library(vroom)
library(ggplot2)
library(xml2)
library(ggrepel)
library(caret)
library(here)
library(igraph)
library(ggtree)
library(hues)
library(ComplexUpset)

knitr::opts_chunk$set(echo = TRUE, root.dir = here::here())

#Define our not in function
`%nin%` <- Negate(`%in%`)
```

# MobSuite Processing

Below we will explore our plasmid data as generated by MobSuite.

## Read in our tree and genomic and metadata dataset

```{r Merge_analysis_outputs, include=FALSE}

genometa <- vroom("delims/genometa_n5631.txt", show_col_types = FALSE)

#Read in our tree
tree <- ggtree::read.tree("analysis/pad.nwk")

#Remove quotes from sample names
tree$tip.label <- gsub("'", "", tree$tip.label)

#Create a list of samples in our cohort
sample_names <- tree$tip.label %>% as.data.frame() %>% rename('name' = '.')

```

## Read in our plasmid cluster data

```{r}
if(!exists("plas_clusters")){
        if(file.exists("delims/plasmid_cluster_data.txt")){
           plas_clusters <- vroom("delims/plasmid_cluster_data.txt")     
        }else{source("scripts/plasmid_data_aggregate.R")}
}
```



## MobTyper Results
```{r}
#Read in our mobtyper data
mobtyper_df <- vroom("analysis/mobtyper_results_concatenated.txt", show_col_types = FALSE)

#Filter in our mobtyper data and rename the sample ID column to name
mobtyper_df <- mobtyper_df %>% rename('name' = sample_id) %>% mutate(name = str_replace(name, ":.*", "")) %>% filter(name %in% tree$tip.label)
```

```{r}
mobtyper_df_tree <- mobtyper_df %>%
  filter(primary_cluster_id %in% c("AA176", "AA175", "AA179", "AE638", 
                                   "AA171", "AA337", "AA352", "AA297", 
                                   "AA174", "AA324", "AA315", "AA735")) %>%
  select(name, primary_cluster_id) %>%
  unique() %>%
  mutate(val_col = 1) %>%
  pivot_wider(values_from = "val_col", 
              names_from = "primary_cluster_id", 
              values_fill = 0)

mobtyper_df_tree <- mobtyper_df_tree %>%
  mutate(across(c("AA176", "AA175", "AA179", "AE638"),
         ~if_else(. == 1, "ColV", as.character(.)))) %>%
  mutate(across(c("AA171", "AA337", "AA352", "AA297"),
         ~if_else(. == 1, "senB", as.character(.)))) %>%
  mutate(across(c("AA174", "AA324", "AA315", "AA735"),
         ~if_else(. == 1, "Other", as.character(.))))

```

```{r}
#Overwrite with different colours
source_cols <- c("Companion Animal" = "#59398d",
         "Environmental" = "#709b46",
         "Food" = "#c09f3d",
         "Human" = "#48c595",
         "Livestock" =  "#c26bbc",
         "Wild Animal" = "#b9553d")

#Define our colours for our phylogroups
clermont_cols <- c('#ffe119', '#4363d8', '#f58231', '#dcbeff', '#800000', '#000075', '#9A6324', 'red', '#3cb44b',  'white', '#a9a9a9', 'black')

#Assign our color names for phylogroups
names(clermont_cols) <- c("A", "B1",  "B2", "C", "D", "E", "F", "G", "E or cladeI", "cladeI", "cladeIII", "cladeIV")
```

```{r}
ST_names <- genometa %>% mutate(ST_other = fct_lump_n(f = ST_new, n = 20, other_level = "Other ")) %>% group_by(ST_other) %>% tally(sort = T) %>% pull(ST_other)

ST_cols <- iwanthue(length(ST_names))

names(ST_cols) <- ST_names

ST_cols[names(ST_cols) =="Other "] <- "white"
```

```{r}

fim_df <- genometa %>%
  group_by(ST_new) %>%
  mutate(fimtyper..Fimtype = if_else(is.na(fimtyper..Fimtype), "Unknown", fimtyper..Fimtype)) %>%
  mutate(
    fim_cat = as.numeric(as.factor(fimtyper..Fimtype)),
    fim_cat = paste0("fimH group ", fim_cat),
    fim_cat = fct_lump_n(fim_cat, n = 4, ties.method = "first", other_level = "Other")
  ) %>%
  select(name, ST_new, fimtyper..Fimtype, fim_cat) %>%
  arrange(ST_new, fim_cat) %>% 
  mutate(fim_cat = as.character(fim_cat))

df_bind <- fim_df[1:ncol(fim_df),] 

df_bind[,1:ncol(df_bind)] <- NA

for(ST in unique(fim_df$ST_new)){
  tmp <- fim_df %>% filter(ST_new == ST) %>%
    arrange(fim_cat) %>%
    mutate(fim_cat = as.numeric(as.factor(fim_cat)))
    
  df_bind <- bind_rows(df_bind, tmp)
}

df_bind <- df_bind[complete.cases(df_bind),]

df_bind <- df_bind %>%
  mutate(fim_cat = as.character(fim_cat)) %>%
  mutate(
    fim_cat = case_when(
      fim_cat == 1 ~ "A ",
      fim_cat == 2  ~ "B ",
      fim_cat == 3  ~ "C ",
      fim_cat == 4  ~ "D ",
      fim_cat == 5  ~ "Other   ",
      TRUE ~ fim_cat  # Keeping "Other" or any additional categories as they are
    )
  )

df_bind <- df_bind %>% ungroup() %>% select(name, fim_cat) %>% rename("Fim Group" = fim_cat)

blacks <- colorRampPalette(c('white', 'black'))

fim_group_cols <- iwanthue(5)

names(fim_group_cols) <- sort(unique(df_bind$`Fim Group`))

```

# Figure 2 - Part A
```{r Part A, echo=FALSE}
#Create the tree
p2 <- ggtree(tree,
        layout = 'circular',
        open.angle = 0) %<+%
        genometa

source_phylogroup_df <- p2$data %>% filter(isTip == TRUE) %>% select(label, Revised_Source_Niche, clermontyping..clermontyping_phylogroup) %>% rename('name' = 'label')

ST_df <- genometa %>% mutate(ST_other = fct_lump_n(f = ST_new, n = 20, other_level = "Other ")) %>% select(name, ST_other)

mobtyper_df_tree_2 <- left_join(source_phylogroup_df, ST_df, by = "name") %>% left_join(mobtyper_df_tree, by = "name") %>% column_to_rownames("name")

p3 <- gheatmap(
        p = p2,
        data = mobtyper_df_tree_2,
        colnames_offset_y = -0.1,
        font.size = 1.5,
        hjust = 0,
        colnames = TRUE,
        offset = 1,
        width = 1,
        color = rgb(220, 220, 220, max = 255, alpha = 30)
        ) +
theme(legend.position = "right") +#,
        #legend.box = "vertical",
        #legend.key.size = unit(1, "mm"),
        #legend.title = element_blank(),
        #legend.text = element_text(size = 8)
        #) +
scale_fill_manual(
        values = c(c("ColV" = 'red', "senB" = 'blue', 'Other' = 'yellow'),
                   source_cols,
                   clermont_cols,
                   ST_cols#,
                   #fim_group_cols
                   ),
        na.value = 'white'
        )
```

```{r}
detected_clusters <- plas_clusters %>% filter(primary_cluster_id %in% unique(mobtyper_df$primary_cluster_id))


ST_entropy<- genometa %>%
        group_by(ST_new) %>%
        add_count(name = 'Count_of_ST') %>%
        ungroup() %>%
        select(name, ST_new, Count_of_ST) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(ST_new, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_ST) %>%
        unique() %>%
        group_by(ST_new, primary_cluster_id) %>% 
        mutate(ST_cluster_prob = counts/Count_of_ST) %>%
        mutate(log_ST_cluster_prob = log(ST_cluster_prob)) %>%
        mutate(prod_ST_cluster_prob_and_log = ST_cluster_prob*log_ST_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_ST_cluster_prob_and_log))) %>%
        mutate('ST_entropy' = entropy) %>% select(primary_cluster_id, ST_entropy) %>% unique()

Phylogroup_entropy <- genometa %>%
        group_by(Consensus_phylogroup) %>%
        add_count(name = 'Count_of_Phylogroup') %>%
        ungroup() %>%
        select(name, Consensus_phylogroup, Count_of_Phylogroup) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(Consensus_phylogroup, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_Phylogroup) %>%
        unique() %>%
        group_by(Consensus_phylogroup, primary_cluster_id) %>% 
        mutate(Phylogroup_cluster_prob = counts/Count_of_Phylogroup) %>%
        mutate(log_Phylogroup_cluster_prob = log(Phylogroup_cluster_prob)) %>%
        mutate(prod_Phylogroup_cluster_prob_and_log = Phylogroup_cluster_prob*log_Phylogroup_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_Phylogroup_cluster_prob_and_log))) %>%
        mutate('Phylogroup_entropy' = entropy) %>%
        select(primary_cluster_id, Phylogroup_entropy) %>% unique()

Source_entropy<- genometa %>%
        group_by(Revised_Source_Niche) %>%
        add_count(name = 'Count_of_Revised_Source_Niche') %>%
        ungroup() %>%
        select(name, Revised_Source_Niche, Count_of_Revised_Source_Niche) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(Revised_Source_Niche, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_Revised_Source_Niche) %>%
        unique() %>%
        group_by(Revised_Source_Niche, primary_cluster_id) %>% 
        mutate(Revised_Source_Niche_cluster_prob = counts/Count_of_Revised_Source_Niche) %>%
        mutate(log_Revised_Source_Niche_cluster_prob = log(Revised_Source_Niche_cluster_prob)) %>%
        mutate(prod_Revised_Source_Niche_cluster_prob_and_log = Revised_Source_Niche_cluster_prob*log_Revised_Source_Niche_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_Revised_Source_Niche_cluster_prob_and_log))) %>%
        mutate('Source_entropy' = entropy) %>% select(primary_cluster_id, Source_entropy) %>% unique()

detected_clusters_w_entropy <- left_join(detected_clusters, Phylogroup_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% left_join(., ST_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% left_join(., Source_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% select(sample_id, matches("entropy"), Plasmid_CIA_status, Plasmid_count_of_AMR_genes, Plasmid_VF_count, matches("^inc"), `IncF RST`, everything()) %>%
        mutate(Plasmid_CIA_status = replace_na(Plasmid_CIA_status, 0)) %>%
        mutate(Plasmid_count_of_AMR_genes = replace_na(Plasmid_count_of_AMR_genes, 0)) %>%
        mutate(Plasmid_VF_count = replace_na(Plasmid_VF_count, 0))
```


```{r}

# Process the data frame `plas_clusters`
replicons <- detected_clusters_w_entropy %>%
  # Select only the necessary columns
  select(sample_id, `rep_type(s)`) %>%
  
  # Expand rows where 'rep_type(s)' contains comma-separated values
  separate_rows(`rep_type(s)`, sep = ',') %>%
  
  # Add a column to represent presence of each replicon type
  mutate(val_col = 1) %>%
  
  # Remove duplicate rows to avoid redundant data
  unique() %>%
  
  # Remove unwanted rows, including those with `-`, `NA`, or any name pattern matching 'rep_cluster'
  filter(!grepl("^-$", `rep_type(s)`)) %>% 
  #filter(!grepl("NA", `rep_type(s)`)) %>% 
  filter(!grepl("rep_cluster*", `rep_type(s)`)) %>% 
  
  #Take the top 20 clusters
  mutate(`rep_type(s)` = fct_lump_n(`rep_type(s)`, 20)) %>%
  
  # Reshape the data from long to wide format
  pivot_wider(
    names_from = `rep_type(s)`,  # Use each replicon type as a separate column
    values_from = val_col,       # Populate with the value from `val_col`
    values_fill = 0              # Fill missing combinations with 0
  ) %>%
  
  # Convert the `sample_id` column into row names
  column_to_rownames('sample_id') %>%
  
  # Sort columns alphabetically
  select(order(colnames(.)))

#Save column names from replicon table
rep_cols <- replicons %>% colnames()

replicons <- replicons %>% rownames_to_column('sample_id')

replicons <- detected_clusters_w_entropy %>% select(sample_id, Plasmid_count_of_AMR_genes, Plasmid_VF_count, Phylogroup_entropy, Source_entropy, size) %>% mutate(size = size/1000) %>% inner_join(replicons, by = "sample_id")

# Generate an upset plot with ComplexUpset to visualize intersections
upset_plot <- ComplexUpset::upset(
  replicons,
  intersect = rep_cols,  # Use all column names in the intersections
  #annotations = list(
  #      'Phylogroup_entropy'=list(
  #          aes=aes(x=intersection, y=Phylogroup_entropy),
  #          geom=geom_boxplot(na.rm=TRUE)
  #      )
  #  ),
  set_sizes=(
        upset_set_size()
        + geom_text(aes(label=..count..), hjust=1.1, stat='count', size = 1.5)
        # you can also add annotations on top of bars:
        + annotate(geom='text', label='@', x='Drama', y=850, color='white', size=3)
        + expand_limits(y=1100)
        + theme(axis.text.x=element_text(angle=90))
    ),
  sort_intersections=FALSE, 
  sort_sets=FALSE,
  min_size = 8,
  matrix=(
        intersection_matrix(
            geom=geom_point(
                shape='square',
                size=1
            ))),
  queries=list(
    upset_query(
            intersect=c('IncHI1B', 'IncFIB'),
            fill='yellow'
        )))

upset_plot + 
  #geom_point(size = 1, aes(size = I(intersection_size))) +
  scale_size_manual(values = c(1))
```

```{r}

# Process the data frame `plas_clusters`
replicons <- mobtyper_df %>%
  
  #Combine Name and Primary Cluster ID
  mutate(name_clust = paste(name, primary_cluster_id)) %>% 
  
  # Select only the necessary columns
  select(name_clust, `rep_type(s)`) %>%
  
  # Expand rows where 'rep_type(s)' contains comma-separated values
  separate_rows(`rep_type(s)`, sep = ',') %>%
  
  # Add a column to represent presence of each replicon type
  mutate(val_col = 1) %>%
  
  # Remove duplicate rows to avoid redundant data
  unique() %>%
  
  #Take the top 20 clusters
  mutate(`rep_type(s)` = str_replace(`rep_type(s)`, "^rep_cluster.*", "Other Rep Clusters")) %>%
  
  #Take the top 20 clusters
  mutate(`rep_type(s)` = str_replace(`rep_type(s)`, "^-$", "No Rep Detected*")) %>%
  
  # Remove duplicate rows to avoid redundant data
  unique() %>%
  
  # Reshape the data from long to wide format
  pivot_wider(
    names_from = `rep_type(s)`,  # Use each replicon type as a separate column
    values_from = val_col,       # Populate with the value from `val_col`
    values_fill = 0              # Fill missing combinations with 0
  ) %>%
  
  # Convert the `name_clust` column into row names
  column_to_rownames('name_clust') %>%
  
  # Sort columns alphabetically
  select(order(colnames(.)))

#Save column names from replicon table
rep_cols <- replicons %>% colnames()

#replicons$`Primary Plasmid Cluster` <- gsub(".* ", "", rownames(replicons))

replicons <- replicons %>% rownames_to_column('rownem') %>% mutate(`Primary Plasmid Cluster` = str_replace(rownem, "novel_.*", "Novel")) %>% mutate(`Primary Plasmid Cluster` = str_replace(`Primary Plasmid Cluster`, ".* ", "")) %>% column_to_rownames('rownem') %>% mutate(`Primary Plasmid Cluster` = fct_lump_n(`Primary Plasmid Cluster`, 21))

top20_cols <- iwanthue(length(sort(unique(replicons$`Primary Plasmid Cluster`))))

names(top20_cols) <- as.character(sort(unique(replicons$`Primary Plasmid Cluster`)))

# Generate an upset plot with ComplexUpset to visualize intersections
upset_plot <- ComplexUpset::upset(
  replicons,
  intersect = rep_cols,  # Ensure this is defined correctly
  base_annotations = list(
        'Plasmids with Replicon Combination (n)' = intersection_size(
            counts = T,
            mapping = aes(fill=`Primary Plasmid Cluster`),
            text_colors = c(on_background = "black", on_bar = "black"),
            #mode = "count",  # Assuming mode should be 'count' if not define appropriately
            #mapping = aes(fill = exclusive_intersection),  # Assuming you fill based on rep_cols or adjust as needed
            size = 2,
            text = list(check_overlap = TRUE, size = 1.5),
            position = position_stack(vjust = 0)
        ) +  scale_fill_manual(values=top20_cols
        )#+ geom_text(stat="count", aes(label=..count..), vjust = -1)
    ),
  set_sizes = (
        upset_set_size()
        + geom_text(aes(label = ..count..), hjust = 1.1, stat = 'count', size = 3)
        + ylim(c(10000, 0))
        + theme(axis.text.x = element_text(angle = 90))
    ),
  sort_intersections = FALSE, 
  sort_sets = FALSE,
  min_size = 40,
  matrix = (
        intersection_matrix(
            geom = geom_point(
                shape = 'square',
                size = 1
            )
        )
    ),
  width_ratio = 0.2,
  guides='over'
)


upset_plot + 
  #geom_point(size = 1, aes(size = I(intersection_size))) +
  scale_size_manual(values = c(1))
```

```{r}
cluster_freq <- replicons %>% group_by(`Primary Plasmid Cluster`) %>% add_count() %>% select(`Primary Plasmid Cluster`, n) %>% unique() %>% arrange(desc(n)) %>% ungroup() %>% mutate(perc = scales::percent(n/sum(.$n)))


genometa %>% select(name, Revised_Source_Niche) %>% full_join(mobtyper_df, by = 'name') %>%
    mutate(`Primary Plasmid Cluster` = fct_lump_n(primary_cluster_id, 20)) %>%
    select(name, Revised_Source_Niche, primary_cluster_id, `Primary Plasmid Cluster`) %>% mutate(val_col = 1) %>% select(-name) %>% pivot_wider(values_from = val_col, names_from = Revised_Source_Niche, values_fill = 0, values_fn = sum) %>% inner_join(cluster_freq) %>% rename("Total" = 'n') %>% arrange(desc(Total))


genometa %>% select(name, Revised_Source_Niche) %>% full_join(mobtyper_df, by = 'name') %>%
    mutate(`Primary Plasmid Cluster` = fct_lump_n(primary_cluster_id, 20)) %>% separate_rows(`rep_type(s)`, sep = ',') %>%select(`Primary Plasmid Cluster`, `rep_type(s)`) %>% mutate(valcol = 1) %>%  #Take the top 20 clusters
mutate(`rep_type(s)` = str_replace(`rep_type(s)`, "^rep_cluster.*", "Other Rep Clusters")) %>%
    
    #Take the top 20 clusters
    mutate(`rep_type(s)` = str_replace(`rep_type(s)`, "^-$", "No Rep Detected*")) %>%
  pivot_wider(values_from = valcol, names_from = `rep_type(s)`, values_fill = 0, values_fn = sum)
```

