---
title: "AusTrakka Tree"
author: "Max Cummins"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: spacelab
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
#Set wd to directory containing current markdown script
knitr::opts_chunk$set(dirname(rstudioapi::getSourceEditorContext()$path))

#Read in our packages
library(tidyverse)
library(vroom)
library(ggplot2)
library(xml2)
library(ggtree)
library(paletteer)

#Define our not in function
`%nin%` <- Negate(`%in%`)
```

```{r}

#Read in our genometa sheet generated by AusTrakka_TEA_data_generation.Rmd
genometa <- vroom("../delims/genometa_n5631.txt", show_col_types = FALSE)

#Read in our tree
tree <- ggtree::read.tree("../analysis/TEA/cgmlst_coreugate/pad.nwk")

#Remove quotes from sample names
tree$tip.label <- gsub("'", "", tree$tip.label)

#Create a list of samples in our cohort
sample_names <- tree$tip.label %>% as.data.frame() %>% rename('name' = '.')
```

## Figure 1 - Part A
```{r Part A, echo=FALSE}
#Anne to provide scatterplot code

```

## Figure 1 - Part B
```{r Part A, echo=FALSE}
#Anne to provide alluvial code

```
