---
title: "AusTrakka Tree"
author: "Max Cummins"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: spacelab
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
#Set wd to directory containing current markdown script
knitr::opts_chunk$set(dirname(rstudioapi::getSourceEditorContext()$path))

#Read in our packages
library(tidyverse)
library(vroom)
library(ggplot2)
library(xml2)
library(ggtree)
library(paletteer)

#Define our not in function
`%nin%` <- Negate(`%in%`)
```

```{r}

#Read in our genometa sheet generated by AusTrakka_TEA_data_generation.Rmd
genometa <- vroom("../delims/genometa_n5631.txt", show_col_types = FALSE)

#Read in our tree
tree <- ggtree::read.tree("../analysis/TEA/cgmlst_coreugate/pad.nwk")

#Remove quotes from sample names
tree$tip.label <- gsub("'", "", tree$tip.label)

#Create a list of samples in our cohort
sample_names <- tree$tip.label %>% as.data.frame() %>% rename('name' = '.')
```

```{r}
#Overwrite with different colours
source_cols <- c("Companion Animal" = "#59398d",
         "Environmental" = "#709b46",
         "Food" = "#c09f3d",
         "Human" = "#48c595",
         "Livestock" =  "#c26bbc",
         "Wild Animal" = "#b9553d")

#Define our colours for our phylogroups
clermont_cols <- c('#ffe119', '#4363d8', '#f58231', '#dcbeff', '#800000', '#000075', '#9A6324', 'red', '#3cb44b',  'white', '#a9a9a9', 'black')

#Assign our color names for phylogroups
names(clermont_cols) <- c("A", "B1",  "B2", "C", "D", "E", "F", "G", "E or cladeI", "cladeI", "cladeIII", "cladeIV")
```

# Figure 2 - Part A
```{r Part A, echo=FALSE}
#Create the tree
p2 <- ggtree(tree,
        layout = 'circular',
        open.angle = 0) %<+%
        genometa

source_phylogroup_df <- p2$data %>% filter(isTip == TRUE) %>% select(label, Revised_Source_Niche, clermontyping..clermontyping_phylogroup) %>% column_to_rownames('label')

p3 <- gheatmap(
        p = p2,
        data = source_phylogroup_df,
        colnames_offset_y = -0.1,
        font.size = 1.5,
        hjust = 0,
        colnames = TRUE,
        offset = 1,
        width = 0.3,
        color = rgb(220, 220, 220, max = 255, alpha = 50)
        ) +
theme(legend.position = "right") +#,
        #legend.box = "vertical",
        #legend.key.size = unit(1, "mm"),
        #legend.title = element_blank(),
        #legend.text = element_text(size = 8)
        #) +
scale_fill_manual(
        values = c(source_cols, clermont_cols),
        na.value = 'grey'
        )
```

## Figure 2 - Part B

```{r Part B, echo=FALSE}
#Anne to provide
```

## Figure 2 - Part C

```{r Part C, echo=FALSE}
#Anne to provide
```