---
title: "AusTrakka_plasmid_gene_correlation"
author: "Max Cummins"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: spacelab
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Read in our packages
library(tidyverse)
library(vroom)
library(ggplot2)
library(xml2)
library(ggrepel)
library(caret)

#Define our not in function
`%nin%` <- Negate(`%in%`)
```

# MobSuite Processing

Below we will explore our plasmid data as generated by MobSuite.

## Read in our tree and genomic and metadata dataset

```{r Merge_analysis_outputs, include=FALSE}
genometa <- vroom("delims/genometa_n5631.txt", show_col_types = FALSE)

#Read in our tree
tree <- ggtree::read.tree("analysis/TEA/cgmlst_coreugate/pad.nwk")

#Remove quotes from sample names
tree$tip.label <- gsub("'", "", tree$tip.label)

#Create a list of samples in our cohort
sample_names <- tree$tip.label %>% as.data.frame() %>% rename('name' = '.')
```

## Read in our plasmid cluster data

```{r}
if(!exists("clusters")){
        if(file.exists("delims/plasmid_cluster_data.txt")){
           clusters <- vroom("delims/plasmid_cluster_data.txt")     
        }else{source("scripts/plasmid_data_aggregate.R")}
}
```



## MobTyper Results
```{r}
#Read in our mobtyper data
mobtyper_df <- vroom("analysis/TEA/mobtyper_results_concatenated.txt", show_col_types = FALSE)

#Filter in our mobtyper data and rename the sample ID column to name
mobtyper_df <- mobtyper_df %>% rename('name' = sample_id) %>% mutate(name = str_replace(name, ":.*", "")) %>% filter(name %in% tree$tip.label)
```


## Entropy attempt
```{r}
detected_clusters <- clusters %>% filter(primary_cluster_id %in% unique(mobtyper_df$primary_cluster_id))


ST_entropy<- genometa %>%
        group_by(ST_new) %>%
        add_count(name = 'Count_of_ST') %>%
        ungroup() %>%
        select(name, ST_new, Count_of_ST) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(ST_new, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_ST) %>%
        unique() %>%
        group_by(ST_new, primary_cluster_id) %>% 
        mutate(ST_cluster_prob = counts/Count_of_ST) %>%
        mutate(log_ST_cluster_prob = log(ST_cluster_prob)) %>%
        mutate(prod_ST_cluster_prob_and_log = ST_cluster_prob*log_ST_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_ST_cluster_prob_and_log))) %>%
        mutate('ST_entropy' = entropy) %>% select(primary_cluster_id, ST_entropy) %>% unique()

Phylogroup_entropy <- genometa %>%
        group_by(Consensus_phylogroup) %>%
        add_count(name = 'Count_of_Phylogroup') %>%
        ungroup() %>%
        select(name, Consensus_phylogroup, Count_of_Phylogroup) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(Consensus_phylogroup, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_Phylogroup) %>%
        unique() %>%
        group_by(Consensus_phylogroup, primary_cluster_id) %>% 
        mutate(Phylogroup_cluster_prob = counts/Count_of_Phylogroup) %>%
        mutate(log_Phylogroup_cluster_prob = log(Phylogroup_cluster_prob)) %>%
        mutate(prod_Phylogroup_cluster_prob_and_log = Phylogroup_cluster_prob*log_Phylogroup_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_Phylogroup_cluster_prob_and_log))) %>%
        mutate('Phylogroup_entropy' = entropy) %>%
        select(primary_cluster_id, Phylogroup_entropy) %>% unique()

Source_entropy<- genometa %>%
        group_by(Revised_Source_Niche) %>%
        add_count(name = 'Count_of_Revised_Source_Niche') %>%
        ungroup() %>%
        select(name, Revised_Source_Niche, Count_of_Revised_Source_Niche) %>%
        inner_join(mobtyper_df, by = "name") %>%
        group_by(Revised_Source_Niche, primary_cluster_id) %>%
        summarise(counts = n(), Count_of_Revised_Source_Niche) %>%
        unique() %>%
        group_by(Revised_Source_Niche, primary_cluster_id) %>% 
        mutate(Revised_Source_Niche_cluster_prob = counts/Count_of_Revised_Source_Niche) %>%
        mutate(log_Revised_Source_Niche_cluster_prob = log(Revised_Source_Niche_cluster_prob)) %>%
        mutate(prod_Revised_Source_Niche_cluster_prob_and_log = Revised_Source_Niche_cluster_prob*log_Revised_Source_Niche_cluster_prob) %>%
        group_by(primary_cluster_id) %>%
        mutate(entropy = abs(sum(prod_Revised_Source_Niche_cluster_prob_and_log))) %>%
        mutate('Source_entropy' = entropy) %>% select(primary_cluster_id, Source_entropy) %>% unique()

detected_clusters_w_entropy <- left_join(detected_clusters, Phylogroup_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% left_join(., ST_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% left_join(., Source_entropy, by = "primary_cluster_id", relationship = "many-to-many") %>% select(sample_id, matches("entropy"), Plasmid_CIA_status, Plasmid_count_of_AMR_genes, Plasmid_VF_count, matches("^inc"), `IncF RST`, everything()) %>%
        mutate(Plasmid_CIA_status = replace_na(Plasmid_CIA_status, 0)) %>%
        mutate(Plasmid_count_of_AMR_genes = replace_na(Plasmid_count_of_AMR_genes, 0)) %>%
        mutate(Plasmid_VF_count = replace_na(Plasmid_VF_count, 0))

plot_df <- detected_clusters_w_entropy %>%
        group_by(primary_cluster_id) %>%
        add_count(`rep_type(s)`) %>%
        #filter(primary_cluster_id %in% mobtyper_results$primary_cluster_id) %>%
        #Identify the most common replicon types within the remaning plasmids
        mutate(Major_reps = `rep_type(s)`[n == max(n)][1]) %>%
        select(-n) %>%
        add_count(`IncF RST`) %>%
        #filter(primary_cluster_id %in% mobtyper_results$primary_cluster_id) %>%
        #Identify the most common replicon types within the remaning plasmids
        mutate(Major_IncF_RST = `IncF RST`[n == max(n)][1]) %>%
        mutate(median_cluster_AMR_gene_count = median(Plasmid_count_of_AMR_genes)) %>%
        as.data.frame() %>% 
        group_by(primary_cluster_id) %>% 
        summarise(primary_cluster_id,
                  median_size = median(size),
                  Phylogroup_entropy,
                  ST_entropy,
                  Source_entropy,
                  Major_reps,
                  Major_IncF_RST,
                  median_VF_count = median(Plasmid_VF_count),
                  median_ARG_count = median(Plasmid_count_of_AMR_genes),
        ) %>%
        unique() 

plot_df <- mobtyper_df %>% group_by(primary_cluster_id) %>% add_count(name = "Total cluster members") %>% select(primary_cluster_id, `Total cluster members`) %>% inner_join(plot_df)


#plot_df %>% arrange(desc(`Total cluster members`)) %>% group_by(primary_cluster_id) %>% slice_head(n = 1) %>% ggplot() +
#        geom_point(aes(x = Phylogroup_entropy, y = median_VF_count, color = predicted_mobility)) +
#        scale_fill_manual(values = c('conjugative' = "red", 'non-conjugative' = 'blue', 'non-mobalizable' = 'green')) +
#        geom_text_repel(aes(x = Phylogroup_entropy, y = median_VF_count, label = primary_cluster_id))


```


```{r}
AA176_APG <- mobtyper_df %>% filter(primary_cluster_id == "AA171")

AA176_plasdb <- clusters %>% filter(primary_cluster_id == "AA171")

AA176_plasdb <- AA176_plasdb %>% select(sample_id, primary_cluster_id, matches("vfdb"))

AA176_plasdb <- AA176_plasdb[, colSums(AA176_plasdb != 0) > 0]

AA176_APG <- genometa %>% select(name, any_of(colnames(AA176_plasdb))) %>% filter(name %in% AA176_APG$name)


AA176_plasdb <- AA176_plasdb %>% mutate(sample_id = paste(sample_id, primary_cluster_id)) %>% column_to_rownames('sample_id') %>% select( -primary_cluster_id)

AA176_APG <- AA176_APG %>% column_to_rownames('name') 

AA176_plasdb <- AA176_plasdb %>% select(any_of(colnames(AA176_APG)))

df <- bind_rows(AA176_APG, AA176_plasdb)

```

```{r}

plasmid_matrix <- AA176_plasdb
genome_matrix <- AA176_APG

# Calculate Jaccard similarity between two binary vectors
jaccard_similarity <- function(vector1, vector2) {
  intersect_count <- sum(vector1 == 1 & vector2 == 1)
  union_count <- sum(vector1 == 1 | vector2 == 1)
  return (intersect_count / union_count)
}

# Initialize an empty matrix to hold similarity scores
num_plasmids <- nrow(plasmid_matrix)
num_genomes <- nrow(genome_matrix)
similarity_matrix <- matrix(0, nrow=num_plasmids, ncol=num_genomes)

# Populate the similarity_matrix with Jaccard similarity scores
for(i in 1:num_plasmids) {
        print(i)
  for(j in 1:num_genomes) {
    similarity_matrix[i, j] <- jaccard_similarity(plasmid_matrix[i, ], genome_matrix[j, ])
  }
}

colnames(similarity_matrix) <- rownames(genome_matrix)
rownames(similarity_matrix) <- rownames(plasmid_matrix)

pheatmap(similarity_matrix)

plotme <- apply(X = similarity_matrix, FUN = max, MARGIN = 2) %>% as.data.frame()

plotme <- plotme %>% rename('score' = '.') %>% mutate(test = 'Virulence')

plotme %>% ggplot() + geom_boxplot(aes(x = score, y = test))

```


```{r}
AA176_APG <- mobtyper_df %>% filter(primary_cluster_id == "AA171")

AA176_plasdb <- clusters %>% filter(primary_cluster_id == "AA171")

AA176_plasdb <- AA176_plasdb %>% select(sample_id, primary_cluster_id, matches("card"))

AA176_plasdb <- AA176_plasdb[, colSums(AA176_plasdb != 0) > 0]

AA176_APG <- genometa %>% select(name, any_of(colnames(AA176_plasdb))) %>% filter(name %in% AA176_APG$name)

AA176_plasdb <- AA176_plasdb %>% mutate(sample_id = paste(sample_id, primary_cluster_id)) %>% column_to_rownames('sample_id') %>% select( -primary_cluster_id)

AA176_APG <- AA176_APG %>% column_to_rownames('name') 

AA176_plasdb <- AA176_plasdb %>% select(any_of(colnames(AA176_APG)))

df <- bind_rows(AA176_APG, AA176_plasdb)
```

```{r}

plasmid_matrix <- AA176_plasdb
genome_matrix <- AA176_APG

# Calculate Jaccard similarity between two binary vectors
jaccard_similarity <- function(vector1, vector2) {
  intersect_count <- sum(vector1 == 1 & vector2 == 1)
  union_count <- sum(vector1 == 1 | vector2 == 1)
  return (intersect_count / union_count)
}

# Initialize an empty matrix to hold similarity scores
num_plasmids <- nrow(plasmid_matrix)
num_genomes <- nrow(genome_matrix)
similarity_matrix <- matrix(0, nrow=num_plasmids, ncol=num_genomes)

# Populate the similarity_matrix with Jaccard similarity scores
for(i in 1:num_plasmids) {
        print(i)
  for(j in 1:num_genomes) {
    similarity_matrix[i, j] <- jaccard_similarity(plasmid_matrix[i, ], genome_matrix[j, ])
  }
}

colnames(similarity_matrix) <- rownames(genome_matrix)
rownames(similarity_matrix) <- rownames(plasmid_matrix)

pheatmap(similarity_matrix, fontsize_col = 2, fontsize_row = 2)

plotme2 <- apply(X = similarity_matrix, FUN = max, MARGIN = 2) %>% as.data.frame()

plotme2 <- plotme2 %>% rename('score' = '.') %>% mutate(test = 'Resistance')

plotme3 <- bind_rows(plotme, plotme2)

plotme3 %>% ggplot() + geom_boxplot(aes(x = score, y = test))

#plotme2$score[complete.cases(plotme$score)] %>% median()

```






```{r}
AA337_APG <- mobtyper_df %>% filter(primary_cluster_id == "AA337")

AA337_plasdb <- clusters %>% filter(primary_cluster_id == "AA337")

AA337_plasdb <- AA337_plasdb %>% select(sample_id, primary_cluster_id, matches("vfdb"), matches("EC_custom"))

AA337_plasdb <- AA337_plasdb[, colSums(AA337_plasdb != 0) > 0]

AA337_APG <- genometa %>% select(name, any_of(colnames(AA337_plasdb))) %>% filter(name %in% AA337_APG$name)


AA337_plasdb <- AA337_plasdb %>% mutate(sample_id = paste(sample_id, primary_cluster_id)) %>% column_to_rownames('sample_id') %>% select( -primary_cluster_id)

AA337_APG <- AA337_APG %>% column_to_rownames('name') 

AA337_plasdb <- AA337_plasdb %>% select(any_of(colnames(AA337_APG)))

df <- bind_rows(AA337_APG, AA337_plasdb)

library(qvalue)
library(jaccard)

```

```{r}

plasmid_matrix <- AA337_plasdb
genome_matrix <- AA337_APG

# Calculate Jaccard similarity between two binary vectors
jaccard_similarity <- function(vector1, vector2) {
  intersect_count <- sum(vector1 == 1 & vector2 == 1)
  union_count <- sum(vector1 == 1 | vector2 == 1)
  return (intersect_count / union_count)
}

# Initialize an empty matrix to hold similarity scores
num_plasmids <- nrow(plasmid_matrix)
num_genomes <- nrow(genome_matrix)
similarity_matrix <- matrix(0, nrow=num_plasmids, ncol=num_genomes)

# Populate the similarity_matrix with Jaccard similarity scores
for(i in 1:num_plasmids) {
        print(i)
  for(j in 1:num_genomes) {
    similarity_matrix[i, j] <- jaccard_similarity(plasmid_matrix[i, ], genome_matrix[j, ])
  }
}

colnames(similarity_matrix) <- rownames(genome_matrix)
rownames(similarity_matrix) <- rownames(plasmid_matrix)

pheatmap(similarity_matrix)

plotme <- apply(X = similarity_matrix, FUN = max, MARGIN = 2) %>% as.data.frame()

plotme <- plotme %>% rename('score' = '.') %>% mutate(test = 1)

plotme %>% ggplot() + geom_boxplot(aes(x = score, y = test))

plotme$score[complete.cases(plotme$score)] %>% median()

```


```{r}
AA337_APG <- mobtyper_df %>% filter(primary_cluster_id == "AA337")

AA337_plasdb <- clusters %>% filter(primary_cluster_id == "AA337")

AA337_plasdb <- AA337_plasdb %>% select(sample_id, primary_cluster_id, matches("card"))

AA337_plasdb <- AA337_plasdb[, colSums(AA337_plasdb != 0) > 0]

AA337_APG <- genometa %>% select(name, any_of(colnames(AA337_plasdb))) %>% filter(name %in% AA337_APG$name)

AA337_plasdb <- AA337_plasdb %>% mutate(sample_id = paste(sample_id, primary_cluster_id)) %>% column_to_rownames('sample_id') %>% select( -primary_cluster_id)

AA337_APG <- AA337_APG %>% column_to_rownames('name') 

AA337_plasdb <- AA337_plasdb %>% select(any_of(colnames(AA337_APG)))

df <- bind_rows(AA337_APG, AA337_plasdb)
```

```{r}

plasmid_matrix <- AA337_plasdb
genome_matrix <- AA337_APG

# Calculate Jaccard similarity between two binary vectors
jaccard_similarity <- function(vector1, vector2) {
  intersect_count <- sum(vector1 == 1 & vector2 == 1)
  union_count <- sum(vector1 == 1 | vector2 == 1)
  return (intersect_count / union_count)
}

# Initialize an empty matrix to hold similarity scores
num_plasmids <- nrow(plasmid_matrix)
num_genomes <- nrow(genome_matrix)
similarity_matrix <- matrix(0, nrow=num_plasmids, ncol=num_genomes)

# Populate the similarity_matrix with Jaccard similarity scores
for(i in 1:num_plasmids) {
        print(i)
  for(j in 1:num_genomes) {
    similarity_matrix[i, j] <- jaccard_similarity(plasmid_matrix[i, ], genome_matrix[j, ])
  }
}

colnames(similarity_matrix) <- rownames(genome_matrix)
rownames(similarity_matrix) <- rownames(plasmid_matrix)

pheatmap(similarity_matrix)

plotme <- apply(X = similarity_matrix, FUN = max, MARGIN = 2) %>% as.data.frame()

plotme <- plotme %>% rename('score' = '.') %>% mutate(test = 1)

plotme %>% ggplot() + geom_boxplot(aes(x = score, y = test))

plotme$score[complete.cases(plotme$score)] %>% median()

```

```{r}
#Read in our mobtyper data
mobtyper_df <- vroom("analysis/TEA/mobtyper_results_concatenated.txt", show_col_types = FALSE)

#Filter in our mobtyper data and rename the sample ID column to name
mobtyper_df <- mobtyper_df %>% rename('name' = sample_id) %>% mutate(name = str_replace(name, ":.*", "")) %>% filter(name %in% tree$tip.label)

abricateR::abricateR(abricate_in = "/Users/131785/Dropbox/PostDoc/Austrakka/AusTrakka_R/analysis/TEA/genotype.txt", output = "TEA_abricate", writecsv = FALSE)

mobtyper_contig_wise <- read_delim("analysis/TEA/mobtyper_results.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)


AA176_APG_names <- mobtyper_df %>% filter(primary_cluster_id == "AA176") %>% pull(name)

#Read in our mobtyper data
mobtyper_contig_wise <- mobtyper_contig_wise %>% rename('name' = sample_id) %>% filter(name %in% AA176_APG_names)

small_mobtyper_hits <- mobtyper_contig_wise %>% select(name, contig_id, primary_cluster_id) %>% mutate(contig_id = str_replace(contig_id, " .*", ""))



co_occurence_df <- TEA_abricate_co_occurence_N90L90 %>% rename('contig_id' = SEQUENCE) %>% inner_join(small_mobtyper_hits, by = c("name", "contig_id"))

co_occurence_df_wide <- co_occurence_df %>%
        group_by(name, primary_cluster_id) %>%
        summarise(same_scaff = paste0(same_scaff, collapse = " ")) %>%
        #filter(primary_cluster_id %in% decat_known_PPCs_known_rep_wide$primary_cluster_id, primary_cluster_id != is.na(primary_cluster_id)) %>%
        mutate(same_scaff2 = strsplit(same_scaff, " ")) %>%
     unnest(same_scaff2) %>% 
     arrange(same_scaff2) %>%  
     pivot_wider(names_from = same_scaff2,
            names_repair = "universal", values_from = same_scaff2, 
        values_fill = 0, values_fn = length)

AA176_scaffolds <- co_occurence_df_wide %>% filter(primary_cluster_id == "AA176")

AA176_plasdb <- clusters %>% filter(primary_cluster_id == "AA176")

AA176_plasdb <- AA176_plasdb %>% select(sample_id, primary_cluster_id, matches("card"), matches("EC_custom"), matches("vfdb"))

AA176_plasdb <- AA176_plasdb[, colSums(AA176_plasdb != 0) > 0]

AA176_plasdb <- AA176_plasdb %>% mutate(sample_id = paste(sample_id, primary_cluster_id)) %>% column_to_rownames('sample_id') %>% select( -primary_cluster_id)

colnames(AA176_plasdb) <- gsub("ABRICATE..", "", colnames(AA176_plasdb))

AA176_scaffolds <- AA176_scaffolds %>% column_to_rownames('name') 

AA176_scaffolds <- AA176_scaffolds %>% select(any_of(colnames(AA176_plasdb)))

AA176_plasdb <- AA176_plasdb %>% select(any_of(colnames(AA176_scaffolds)))

plasmid_matrix <- AA176_plasdb
genome_matrix <- AA176_scaffolds

# Calculate Jaccard similarity between two binary vectors
jaccard_similarity <- function(vector1, vector2) {
  intersect_count <- sum(vector1 == 1 & vector2 == 1)
  union_count <- sum(vector1 == 1 | vector2 == 1)
  return (intersect_count / union_count)
}

# Initialize an empty matrix to hold similarity scores
num_plasmids <- nrow(plasmid_matrix)
num_genomes <- nrow(genome_matrix)
similarity_matrix <- matrix(0, nrow=num_plasmids, ncol=num_genomes)

# Populate the similarity_matrix with Jaccard similarity scores
for(i in 1:num_plasmids) {
        print(i)
  for(j in 1:num_genomes) {
    similarity_matrix[i, j] <- jaccard_similarity(plasmid_matrix[i, ], genome_matrix[j, ])
  }
}

colnames(similarity_matrix) <- rownames(genome_matrix)
rownames(similarity_matrix) <- rownames(plasmid_matrix)

pheatmap(similarity_matrix)

plotme <- apply(X = similarity_matrix, FUN = max, MARGIN = 2) %>% as.data.frame()

plotme <- plotme %>% rename('score' = '.') %>% mutate(test = 1)

plotme %>% ggplot() + geom_boxplot(aes(x = score, y = test))

plotme$score[complete.cases(plotme$score)] %>% median()

```

